"""add projects table

Introduces the ``projects`` table — the bounded pieces of work that
live inside a :class:`Workspace`. The relationship is many-to-one
(Workspace → Projects), enforced server-side via a foreign key with
``ON DELETE CASCADE`` so removing a workspace drops its projects.

Schema
------
* ``id``            UUID v4 primary key (from ``UUIDPrimaryKeyMixin``)
* ``workspace_id``  UUID, FK → ``workspaces.id`` (cascade delete)
* ``name``          VARCHAR(100), NOT NULL
* ``description``   TEXT, nullable
* ``status``        ENUM('planned', 'active', 'paused', 'completed',
                      'archived'), NOT NULL, server_default='planned'
* ``created_at``    TIMESTAMPTZ, NOT NULL, server_default=now()
* ``updated_at``    TIMESTAMPTZ, NOT NULL, server_default=now()

Indexes
-------
* ``ix_projects_workspace_id`` — list-by-workspace queries.
* ``ix_projects_created_at``   — default list ordering (newest first).

Revision ID: 8a344b5ac13d
Revises: abff39cda22e
Create Date: 2026-06-27 21:31:59.061768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a344b5ac13d'
down_revision: Union[str, Sequence[str], None] = 'abff39cda22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'active', 'paused', 'completed', 'archived', name='project_status', length=20), server_default='planned', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
